-- MySQL Script generated by MySQL Workbench
-- Sun Mar  3 01:43:32 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `HarryPotterMDB` DEFAULT CHARACTER SET utf8 ;
USE `HarryPotterMDB` ;

-- -----------------------------------------------------
-- Table `mydb`.`HarryPotterMovies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HarryPotterMDB`.`HarryPotterMovies` (
  `IMDBID` VARCHAR(9) NOT NULL,
  `Title` VARCHAR(60) NOT NULL,
  `Year` INT NOT NULL,
  `ImgUrl` VARCHAR(500) NOT NULL,
  `userRating` INT NOT NULL DEFAULT 0,
  `plot` VARCHAR(500) NOT NULL,
  
  PRIMARY KEY (`IMDBID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

